package TemperatureConversionComplete;
// @author Michael Kester

public class TempConvertComplete extends javax.swing.JFrame {

    String input, output;
    double f2c, f2k, c2f, c2k, k2f, k2c;

    // Creates new form TempConvertComplete
    public TempConvertComplete() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelLabel = new javax.swing.JPanel();
        lblConvertTemp = new javax.swing.JLabel();
        panelTxt = new javax.swing.JPanel();
        txtFTemp = new javax.swing.JTextField();
        lblInstruct = new javax.swing.JLabel();
        lblInstruct2 = new javax.swing.JLabel();
        panelButtons = new javax.swing.JPanel();
        btnFtoC = new javax.swing.JButton();
        btnCtoF = new javax.swing.JButton();
        btnKtoC = new javax.swing.JButton();
        btnFtoK = new javax.swing.JButton();
        btnCtoK = new javax.swing.JButton();
        btnKtoF = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Temperature Conversion [Complete]");
        getContentPane().setLayout(new java.awt.GridLayout(3, 1));

        panelLabel.setLayout(new java.awt.GridLayout(1, 1));

        lblConvertTemp.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblConvertTemp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblConvertTemp.setText("[Converted Temp]");
        panelLabel.add(lblConvertTemp);

        getContentPane().add(panelLabel);

        panelTxt.setLayout(new java.awt.GridLayout(3, 1));

        txtFTemp.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        txtFTemp.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFTemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFTempActionPerformed(evt);
            }
        });
        panelTxt.add(txtFTemp);

        lblInstruct.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblInstruct.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInstruct.setText("Input temperature in Fahrenheit, Celsius, or Kelvin.");
        panelTxt.add(lblInstruct);

        lblInstruct2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblInstruct2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInstruct2.setText("Then press the button that corresponds to the unit you entered.");
        panelTxt.add(lblInstruct2);

        getContentPane().add(panelTxt);

        panelButtons.setLayout(new java.awt.GridLayout(2, 3));

        btnFtoC.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnFtoC.setText("Fahrenheit -> Celsius");
        btnFtoC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFtoCActionPerformed(evt);
            }
        });
        panelButtons.add(btnFtoC);

        btnCtoF.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnCtoF.setText("Celsius -> Fahrenheit");
        btnCtoF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCtoFActionPerformed(evt);
            }
        });
        panelButtons.add(btnCtoF);

        btnKtoC.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnKtoC.setText("Kelvin -> Celsius");
        btnKtoC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKtoCActionPerformed(evt);
            }
        });
        panelButtons.add(btnKtoC);

        btnFtoK.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        btnFtoK.setText("Fahrenheit -> Kelvin");
        btnFtoK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFtoKActionPerformed(evt);
            }
        });
        panelButtons.add(btnFtoK);

        btnCtoK.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnCtoK.setText("Celsius -> Kelvin");
        btnCtoK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCtoKActionPerformed(evt);
            }
        });
        panelButtons.add(btnCtoK);

        btnKtoF.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        btnKtoF.setText("Kelvin -> Fahrenheit");
        btnKtoF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKtoFActionPerformed(evt);
            }
        });
        panelButtons.add(btnKtoF);

        getContentPane().add(panelButtons);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtFTempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFTempActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFTempActionPerformed

    private void btnFtoCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFtoCActionPerformed
        input = txtFTemp.getText();
        double f = Double.parseDouble(input);
        f2c = (5 * (f - 32)) / 9;
        output = String.valueOf(f2c);
        lblConvertTemp.setText(output + " degrees Celsius");
    }//GEN-LAST:event_btnFtoCActionPerformed

    private void btnKtoCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKtoCActionPerformed
        input = txtFTemp.getText();
        double k = Double.parseDouble(input);
        k2c = k - 273.15;
        output = String.valueOf(k2c);
        lblConvertTemp.setText(output + " degrees Celsius");
    }//GEN-LAST:event_btnKtoCActionPerformed

    private void btnFtoKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFtoKActionPerformed
        input = txtFTemp.getText();
        double f = Double.parseDouble(input);
        f2k = (5 * (f + 459.67)) / 9;
        output = String.valueOf(f2k);
        lblConvertTemp.setText(output + " Kelvin");
    }//GEN-LAST:event_btnFtoKActionPerformed

    private void btnCtoFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCtoFActionPerformed
        input = txtFTemp.getText();
        double c = Double.parseDouble(input);
        c2f = (c * 1.8) + 32;
        output = String.valueOf(c2f);
        lblConvertTemp.setText(output + " degrees Fahrenheit");
    }//GEN-LAST:event_btnCtoFActionPerformed

    private void btnCtoKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCtoKActionPerformed
        input = txtFTemp.getText();
        double c = Double.parseDouble(input);
        c2k = c + 273.15;
        output = String.valueOf(c2k);
        lblConvertTemp.setText(output + " Kelvin");
    }//GEN-LAST:event_btnCtoKActionPerformed

    private void btnKtoFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKtoFActionPerformed
        input = txtFTemp.getText();
        double k = Double.parseDouble(input);
        k2f = k * (9.0/5.0) - 459.67;
        output = String.valueOf(k2f);
        lblConvertTemp.setText(output + " degrees Fahrenheit");
    }//GEN-LAST:event_btnKtoFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TempConvertComplete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TempConvertComplete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TempConvertComplete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TempConvertComplete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TempConvertComplete().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCtoF;
    private javax.swing.JButton btnCtoK;
    private javax.swing.JButton btnFtoC;
    private javax.swing.JButton btnFtoK;
    private javax.swing.JButton btnKtoC;
    private javax.swing.JButton btnKtoF;
    private javax.swing.JLabel lblConvertTemp;
    private javax.swing.JLabel lblInstruct;
    private javax.swing.JLabel lblInstruct2;
    private javax.swing.JPanel panelButtons;
    private javax.swing.JPanel panelLabel;
    private javax.swing.JPanel panelTxt;
    private javax.swing.JTextField txtFTemp;
    // End of variables declaration//GEN-END:variables
}
