<!-- Assignments List Box -->
<div id="assignment">
	<div>
		<a href="/~mkester4/IT207">Home</a></br>

		<h4>Lab Assignments</h4>
		<ul>
			<li><a href="/~mkester4/IT207/LAB1/">Assignment 1</a></li>
			<li><a href="/~mkester4/IT207/LAB2/">Assignment 2</a></li>
			<li><a href="/~mkester4/IT207/LAB3/">Assignment 3</a></li>
			<li><a href="/~mkester4/IT207/LAB4/">Assignment 4</a></li>
		</ul>
	</div>

	<div>
		<h4>Lab Practica</h4>
		<ul>
			<li><a href="/~mkester4/IT207/LABP1">Practicum 1</a></li>
			<li><a href ="/~mkester4/IT207/LABP2">Practicum 2</a></li>
		</ul>
	</div>
</div>
