package TemperatureConversion;
// @author Michael Kester

public class TempConvert extends javax.swing.JFrame {
    
    String input;

    // Creates new form TempConvert
    public TempConvert() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelLabel = new javax.swing.JPanel();
        lblCTemp = new javax.swing.JLabel();
        panelTxt = new javax.swing.JPanel();
        txtFTemp = new javax.swing.JTextField();
        lblInstruct = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Temperature Conversion");
        getContentPane().setLayout(new java.awt.GridLayout(2, 1));

        lblCTemp.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblCTemp.setText("[Celsius Temp]");
        panelLabel.add(lblCTemp);

        getContentPane().add(panelLabel);

        panelTxt.setLayout(new java.awt.GridLayout(2, 1));

        txtFTemp.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txtFTemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFTempActionPerformed(evt);
            }
        });
        panelTxt.add(txtFTemp);

        lblInstruct.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblInstruct.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInstruct.setText("Input temperature in Fahrenheit, then press Enter to convert");
        panelTxt.add(lblInstruct);

        getContentPane().add(panelTxt);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtFTempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFTempActionPerformed
        input = txtFTemp.getText();
        int i = Integer.parseInt(input);
        int d = (5 * ( i - 32 ) ) / 9;
        String c = Integer.toString(d);
        lblCTemp.setText(c + " degrees Celsius");
    }//GEN-LAST:event_txtFTempActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TempConvert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TempConvert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TempConvert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TempConvert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TempConvert().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblCTemp;
    private javax.swing.JLabel lblInstruct;
    private javax.swing.JPanel panelLabel;
    private javax.swing.JPanel panelTxt;
    private javax.swing.JTextField txtFTemp;
    // End of variables declaration//GEN-END:variables
}
